### ISSUE TITLE
Endless waiting and no results.

### ISSUE THREAD

**Issue by YordanYanakiev** [jeffdapaz/VisualChatGPTStudio#51]
Hello. I've just installed the plugin over VS2022, generated a ChatGPT code and place it in the options.
Yet i got the progressbar going forever even for a simple request, and nothing. It never results anything just the progressbar going and never stopping. 
![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/6534199/0624ef97-79dd-4b1f-9fb1-0de162316669)

**Comment by jeffdapaz** [comment]
Hi,

you are the second that say that have the same issue. I will investigate and keep here updated with the progress.

**Comment by jeffdapaz** [comment]
@YordanYanakiev and @ghendrikx,

I was trying to figure out what may happening, but no luck. I tried several ways to mess up the my connection but I always got soon an error message.

Because of this I guess it could be something related to OpenAI that refuses to return a response, but I'm not certainly.

Can you check if you can connect to OpenAI API playground and tell me?

[https://platform.openai.com/playground](https://platform.openai.com/playground)

However I made a litlle change and I added two minutes timeout for the requests. This may not solve the problem, but It's a try.

**Comment by YordanYanakiev** [comment]
I am opening this, but I got an error message that I have reached usage limit ? for a new account ?
And it is asking for paid account ?
![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/6534199/ea8d6305-fdd1-4fef-971d-4e82d245a339)

**Comment by jeffdapaz** [comment]
@YordanYanakiev , have you created this account recently?

I remember that in April OpenAI gave US$30.00 in credits for a new account to use within a month, and after a while they reduced it to US$5.00.

Maybe they cut the free trial for new accounts.

I know there are people who have configured another base address and/or configured a proxy to be able to use without paying, but I've never tested it.

The only other alternatives I see are paying to OpenAI or getting access to Azure OpenAI.

EDIT:

I still don't know why, but this is happening with others:

[https://community.openai.com/t/why-i-have-no-free-trial-usage/123757](https://community.openai.com/t/why-i-have-no-free-trial-usage/123757)

[https://community.openai.com/t/free-trial-is-showing-0-0-credit-even-though-no-api-is-called-yet/96128/12](https://community.openai.com/t/free-trial-is-showing-0-0-credit-even-though-no-api-is-called-yet/96128/12)

**Comment by YordanYanakiev** [comment]
Yuuup. All paid now. No more free carrots. :|
