### ISSUE TITLE
Add WordWrap option in response and request fields

### ISSUE THREAD

**Issue by GothicSecret** [jeffdapaz/VisualChatGPTStudio#58]
![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/21962081/f0a8a009-4a29-4d2a-b4da-c52f73a1cae6)

**Comment by jeffdapaz** [comment]
@GothicSecret ,

I don't think that having a word wrap by default in this window is ideal, because it is more focused on displaying codes in the result. If there are always line breaks, code visualization may be impaired due to incorrect indentation.

However, adding a command where it is possible to turn on/turn off word wrap as the user desires is something more desirable.

I will think about this possibility for a next release.

**Comment by jeffdapaz** [comment]
Hi @GothicSecret,

I already added the button that I said. Will be on next release.

**Comment by jeffdapaz** [comment]
@GothicSecret , I already published a new version with the word wrap button.
