### ISSUE TITLE
It is impossible to reset the command line to the original ones

### ISSUE THREAD

**Issue by ViktorAgafonov** [jeffdapaz/VisualChatGPTStudio#76]
In the command settings menu, after creating an empty line, I deleted the default line. When you reinstall the add-on, the settings are not deleted and there is always an empty line instead of commands. How to reset all settings to default?

**Comment by jeffdapaz** [comment]
@ViktorAgafonov, 

for now as workaround you can direct edit the commands file, where is located on \Users\{your user name}\AppData\Local\Visual chatGPT Studio\commands.json.

If there is not commands, you can replace with the default values:

`[
    {
        "ProjectName": "",
        "Complete": "Please complete",
        "AddTests": "Create unit tests",
        "FindBugs": "Find Bugs",
        "Optimize": "Optimize, improve code readbility, fix and improve the code indentation,  improve code performance, fix securities issues, fix any possible bugs, apply changes to turn the code safe against bugs and resilient",
        "Explain": "Explain",
        "AddSummary": "Only write a comment as C# summary format like",
        "AddCommentsForLine": "Comment. Add comment char for each comment line",
        "AddCommentsForLines": "Rewrite the code with comments. Add comment char for each comment line",
        "Translate": "Translate to English",
        "CustomBefore": "",
        "CustomAfter": "",
        "CustomReplace": ""
    }
]`

For me, I will provide a fix because was not supposed to be possible delete the default commands to avoid this situation.

**Comment by jeffdapaz** [comment]
Fix published on last release.
