### ISSUE TITLE
Llama support needed

### ISSUE THREAD

**Issue by zhanggaolei001** [jeffdapaz/VisualChatGPTStudio#77]
I've tried deploying LLaMA 3.1 locally and integrating its API into my extension, but unfortunately, it's not working as expected.
Am I missing a crucial config option?

Here is my settings and output log:
 
![image](https://github.com/user-attachments/assets/401b3cc1-8400-42bc-8331-87bd9536085c)

2024/7/30 9:07:32: Request URI: http://127.0.0.1:11434/v1/chat/completions
2024/7/30 9:07:32: Request Method: POST
2024/7/30 9:07:32: Request Headers:
2024/7/30 9:07:32: Accept-Encoding: gzip, deflate
2024/7/30 9:07:32: Connection: keep-alive
2024/7/30 9:07:32: Authorization: Bearer empty
2024/7/30 9:07:32: api-key: empty
2024/7/30 9:07:32: User-Agent: okgodoit/dotnet_openai_api
2024/7/30 9:07:32: Request Content: {"model":"llama3.1","messages":[{"role":"system","content":"Please complete. Please, only provide the code without additional comments or text. For C#."},{"role":"user","content":"      //二分定位算法示例：\r\n\r\n"}],"temperature":0.0,"top_p":0.0,"n":1,"stream":false,"stop":"","max_tokens":4096,"frequency_penalty":0.5,"presence_penalty":0.0}
2024/7/30 9:07:32: ____________________________________________________________________________________________________
2024/7/30 9:07:33: Response Headers:
2024/7/30 9:07:33: Date: Tue, 30 Jul 2024 01:07:33 GMT
2024/7/30 9:07:33: Response Status Code: OK
2024/7/30 9:07:33: Response Content: {"id":"chatcmpl-337","object":"chat.completion","created":1722301653,"model":"llama3.1","system_fingerprint":"fp_ollama","choices":[{"index":0,"message":{"role":"assistant","content":""},"finish_reason":"stop"}],"usage":{"prompt_tokens":45,"completion_tokens":1,"total_tokens":46}}

2024/7/30 9:07:33: ____________________________________________________________________________________________________

**Comment by jeffdapaz** [comment]
@zhanggaolei001,

as I told elsewhere, I've never tested myself another services than OpenAI or Azure, but seeing your parameterizations and logs,  for me it's looks everything ok. Reading the logs, it's possible to see that the response has the status code "ok", but the content it's coming empty for somehow.

You already tried send an english request? Just to check that the LLM not being answered because your request is in Chinese.

Another suggestion that I can give to you it's trying ask another people that already could connect to LLM successfully. You can find then here:

https://github.com/jeffdapaz/VisualChatGPTStudio/issues/73
https://github.com/jeffdapaz/VisualChatGPTStudio/issues/65

**Comment by jeffdapaz** [comment]
@zhanggaolei001, I will assume that you resolved your issue.

 In another case you can reopen.

**Comment by ViktorAgafonov** [comment]
Maybe this will help somehow. I don't know what to do with this:
https://github.com/awaescher/OllamaSharp
