### ISSUE TITLE
Adding support for Visual Studio Enterprise

### ISSUE THREAD

**Issue by penghao94** [jeffdapaz/VisualChatGPTStudio#83]
Hi Jeff,
Thanks for you good job!
Could you add support for Visual Studio Enterprise? I've check the extension.vsixmandifest and found VS Enterprise was not included.
Many thanks!

**Comment by jeffdapaz** [comment]
Hi @penghao94, very thanks!

About your question, the extension is already compatible with all versions, including enterprise.

Since I only specified the community edition, it means that all versions above will also be compatible.

I have already had the opportunity to test it in all 3 editions (Community, Professional and Enterprise).

**Comment by jeffdapaz** [comment]
@penghao94, I think I've already answered your question, you can open the issue again if necessary.
